### ISSUE TITLE
Bot stops playing after 1 move

### ISSUE THREAD

**Issue by ARipePotato** [LouisAsanaka/PyChessBot#2]
Once the both plays one move it locks up and dosent play any other moves

**Comment by richardmcameron** [comment]
> Once the both plays one move it locks up and dosent play any other moves

Can second this.

`Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.752.0_x64__qbz5n2kfra8p0\lib\tkinter\__init__.py", line 1892, in __call__
    return self.func(*args)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.752.0_x64__qbz5n2kfra8p0\lib\tkinter\__init__.py", line 814, in callit
    func(*args)
  File "C:\Users\Richard\PycharmProjects\PyChess\main.py", line 77, in loop
    move = self.analyzer.analyze_changes(self.analyzer.detect_changes())
  File "C:\Users\Richard\PycharmProjects\PyChess\board\analyzer.py", line 192, in analyze_changes
    squares[i] = Chessboard.get_square(*changed_squares[i], self.board.color)
IndexError: list assignment index out of range`

**Comment by LouisAsanaka** [comment]
I believe the library has been updated. I'll try and fix it soon.

**Comment by LouisAsanaka** [comment]
Should be fixed with the latest commit.
